# Generated by Django 3.0 on 2020-03-19 13:41

from django.db import migrations, models
import django.db.models.deletion
import saree_collection.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=50)),
                ('collection_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SareeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saree_img', stdimage.models.StdImageField(upload_to=saree_collection.models.upload_path)),
                ('collection_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saree_collection.CollectionModel')),
            ],
        ),
    ]
