# Generated by Django 3.0 on 2020-03-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saree_collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='CustomerContactModel',
        ),
    ]
